      // ==================================================
      // CUSTOMER ORDER CREATION
      // POST /api/customer/orders
      // ==================================================

      if (
        url.pathname === "/api/customer/orders" &&
        request.method === "POST"
      ) {
        const body = await request.json();

        const customerId = Number(body.customer_id);
        const customerName = String(body.customer_name || "").trim();
        const customerPhone = String(body.customer_phone || "").trim();
        const orderType = String(body.order_type || "").trim();
        const section = body.section == null
          ? null
          : String(body.section).trim();

        const tableId = body.table_id == null
          ? null
          : String(body.table_id).trim();

        const tableNo = body.table_no == null
          ? null
          : String(body.table_no).trim();

        const subtotal = String(body.subtotal ?? "0");
        const sstTax = String(body.sst_tax ?? "0");
        const totalAmount = Number(body.total_amount);

        const orderNote = body.order_note == null
          ? null
          : String(body.order_note);

        const items = Array.isArray(body.items)
          ? body.items
          : [];

        if (!Number.isInteger(customerId) || customerId <= 0) {
          return json({
            ok: false,
            error: "Customer login is required."
          }, 400);
        }

        if (!customerName) {
          return json({
            ok: false,
            error: "Customer name is required."
          }, 400);
        }

        if (!orderType) {
          return json({
            ok: false,
            error: "Order type is required."
          }, 400);
        }

        if (!Number.isFinite(totalAmount) || totalAmount < 0) {
          return json({
            ok: false,
            error: "Invalid total amount."
          }, 400);
        }

        if (items.length === 0) {
          return json({
            ok: false,
            error: "Order cart is empty."
          }, 400);
        }

        // Make sure customer exists.
        const customer = await env.DB
          .prepare(`
            SELECT id
            FROM customers
            WHERE id = ?
            LIMIT 1
          `)
          .bind(customerId)
          .first();

        if (!customer) {
          return json({
            ok: false,
            error: "Customer not found."
          }, 404);
        }

        // Basic item validation before writing anything.
        for (const item of items) {
          const menuItemId = Number(item.menu_item_id);
          const quantity = Number(item.quantity ?? 1);
          const price = Number(item.price);

          if (
            !Number.isInteger(menuItemId) ||
            menuItemId <= 0 ||
            !Number.isInteger(quantity) ||
            quantity <= 0 ||
            !Number.isFinite(price) ||
            price < 0
          ) {
            return json({
              ok: false,
              error: "Invalid order item."
            }, 400);
          }
        }

        /*
          Two statements are executed as one D1 batch:

          1. Create orders row.
          2. Expand the JSON cart and create all order_items.

          The second statement gets the ID generated by the
          orders AUTOINCREMENT sequence.
        */

        const itemsJson = JSON.stringify(items);

        const statements = [
          env.DB.prepare(`
            INSERT INTO orders (
              customer_id,
              customer_name,
              customer_phone,
              order_type,
              section,
              table_id,
              table_no,
              status,
              payment_status,
              subtotal,
              sst_tax,
              total_amount,
              order_note
            )
            VALUES (
              ?, ?, ?, ?, ?, ?, ?,
              'pending',
              'unpaid',
              ?, ?, ?, ?
            )
          `).bind(
            customerId,
            customerName,
            customerPhone || null,
            orderType,
            section,
            tableId,
            tableNo,
            subtotal,
            sstTax,
            totalAmount,
            orderNote
          ),

          env.DB.prepare(`
            INSERT INTO order_items (
              order_id,
              menu_item_id,
              price,
              quantity,
              modifiers
            )
            SELECT
              (
                SELECT seq
                FROM sqlite_sequence
                WHERE name = 'orders'
              ),
              CAST(
                json_extract(value, '$.menu_item_id')
                AS INTEGER
              ),
              CAST(
                json_extract(value, '$.price')
                AS NUMERIC
              ),
              COALESCE(
                CAST(
                  json_extract(value, '$.quantity')
                  AS INTEGER
                ),
                1
              ),
              COALESCE(
                json_extract(value, '$.modifiers'),
                '[]'
              )
            FROM json_each(?)
          `).bind(itemsJson)
        ];

        const batchResult = await env.DB.batch(statements);

        const orderId =
          batchResult?.[0]?.meta?.last_row_id;

        if (!orderId) {
          throw new Error(
            "Order was created but order ID could not be returned."
          );
        }

        return json({
          ok: true,
          order_id: orderId,
          status: "pending",
          payment_status: "unpaid"
        }, 201);
      }


      // ==================================================
      // PROTECTED ORDERS LIST
      // GET /api/orders
      // ==================================================

      if (
        url.pathname === "/api/orders" &&
        request.method === "GET"
      ) {
        if (!isAuthorized(request, env)) {
          return json({
            ok: false,
            error: "Unauthorized"
          }, 401);
        }

        const status = url.searchParams.get("status");
        const paymentStatus =
          url.searchParams.get("payment_status");

        const tableId =
          url.searchParams.get("table_id");

        let sql = `
          SELECT *
          FROM orders
          WHERE 1 = 1
        `;

        const params = [];

        if (status) {
          sql += ` AND status = ?`;
          params.push(status);
        }

        if (paymentStatus) {
          sql += ` AND payment_status = ?`;
          params.push(paymentStatus);
        }

        if (tableId) {
          sql += ` AND table_id = ?`;
          params.push(tableId);
        }

        sql += `
          ORDER BY created_at DESC, id DESC
          LIMIT 500
        `;

        const stmt = env.DB.prepare(sql);

        const result = params.length
          ? await stmt.bind(...params).all()
          : await stmt.all();

        return json({
          ok: true,
          count: result.results?.length ?? 0,
          orders: result.results ?? []
        });
      }


      // ==================================================
      // PROTECTED SINGLE ORDER
      // GET /api/orders/:id
      // ==================================================

      if (
        /^\/api\/orders\/\d+$/.test(url.pathname) &&
        request.method === "GET"
      ) {
        if (!isAuthorized(request, env)) {
          return json({
            ok: false,
            error: "Unauthorized"
          }, 401);
        }

        const orderId =
          Number(url.pathname.split("/").pop());

        const order = await env.DB
          .prepare(`
            SELECT *
            FROM orders
            WHERE id = ?
            LIMIT 1
          `)
          .bind(orderId)
          .first();

        if (!order) {
          return json({
            ok: false,
            error: "Order not found"
          }, 404);
        }

        const items = await env.DB
          .prepare(`
            SELECT
              oi.*,
              mi.name_en,
              mi.category,
              mi.image_url
            FROM order_items oi
            LEFT JOIN menu_items mi
              ON mi.id = oi.menu_item_id
            WHERE oi.order_id = ?
            ORDER BY oi.id
          `)
          .bind(orderId)
          .all();

        return json({
          ok: true,
          order,
          items: items.results ?? []
        });
      }


      // ==================================================
      // PROTECTED ORDER ITEMS
      // GET /api/orders/:id/items
      // ==================================================

      if (
        /^\/api\/orders\/\d+\/items$/.test(url.pathname) &&
        request.method === "GET"
      ) {
        if (!isAuthorized(request, env)) {
          return json({
            ok: false,
            error: "Unauthorized"
          }, 401);
        }

        const parts = url.pathname.split("/");
        const orderId = Number(parts[3]);

        const result = await env.DB
          .prepare(`
            SELECT
              oi.*,
              mi.name_en,
              mi.category,
              mi.image_url
            FROM order_items oi
            LEFT JOIN menu_items mi
              ON mi.id = oi.menu_item_id
            WHERE oi.order_id = ?
            ORDER BY oi.id
          `)
          .bind(orderId)
          .all();

        return json({
          ok: true,
          count: result.results?.length ?? 0,
          items: result.results ?? []
        });
      }


      // ==================================================
      // PROTECTED ORDER UPDATE
      // PATCH /api/orders/:id
      // ==================================================

      if (
        /^\/api\/orders\/\d+$/.test(url.pathname) &&
        request.method === "PATCH"
      ) {
        if (!isAuthorized(request, env)) {
          return json({
            ok: false,
            error: "Unauthorized"
          }, 401);
        }

        const orderId =
          Number(url.pathname.split("/").pop());

        const body = await request.json();

        const allowedFields = [
          "status",
          "payment_status",
          "customer_name",
          "customer_phone",
          "section",
          "table_id",
          "table_no",
          "subtotal",
          "sst_tax",
          "total_amount",
          "decline_reason",
          "order_note",
          "accepted_by_id",
          "accepted_by_name",
          "accepted_by_email",
          "accepted_by_role",
          "accepted_at",
          "declined_by_id",
          "declined_by_name",
          "declined_by_email",
          "declined_by_role",
          "declined_at",
          "cancelled_by_id",
          "cancelled_by_name",
          "cancelled_by_email",
          "cancelled_by_role",
          "cancelled_at",
          "cancel_reason"
        ];

        const updates = [];
        const values = [];

        for (const field of allowedFields) {
          if (
            Object.prototype.hasOwnProperty.call(
              body,
              field
            )
          ) {
            updates.push(`${field} = ?`);
            values.push(body[field]);
          }
        }

        if (updates.length === 0) {
          return json({
            ok: false,
            error: "No valid fields supplied"
          }, 400);
        }

        values.push(orderId);

        const result = await env.DB
          .prepare(`
            UPDATE orders
            SET ${updates.join(", ")}
            WHERE id = ?
          `)
          .bind(...values)
          .run();

        if (!result.meta?.changes) {
          return json({
            ok: false,
            error: "Order not found or not updated"
          }, 404);
        }

        const order = await env.DB
          .prepare(`
            SELECT *
            FROM orders
            WHERE id = ?
          `)
          .bind(orderId)
          .first();

        return json({
          ok: true,
          order
        });
      }
